services:
  - type: worker
    name: n8n
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_TUNNEL_URL
        sync: false
      - key: N8N_PORT
        value: 5678
